# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('access_key_id', models.TextField(max_length=512)),
                ('secrete_key', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('url', models.TextField(max_length=512)),
                ('arn', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('topic', models.TextField(max_length=512)),
                ('dl_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_queue_fk', to='stack.Queue')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_fk', to='stack.IAM')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_fk', to='stack.Queue')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retriever_fk', to='stack.IAM')),
            ],
        ),
    ]
