# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('arn', models.TextField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='stack',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.Topic'),
        ),
    ]
