# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_auto_20170318_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iam',
            old_name='secrete_key',
            new_name='secret_key',
        ),
    ]
