# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_auto_20170318_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='receiver',
            new_name='retriever',
        ),
    ]
